// packages/db/scripts/seed.js
// Golden record fixtures for CI regression + demo path.
// 25 permits spanning 5 cities, various work types, valuation range.

const fixtures = [
  // ---- Chicago ----
  {
    city: "chicago",
    source_permit_id: "CHI-2024-001",
    filed_date: "2024-01-15",
    issued_date: "2024-02-20",
    address_raw: "123 N Michigan Ave Chicago IL 60601",
    address_norm: "123 n michigan ave chicago il 60601",
    work_type: "commercial",
    description_raw: "Interior renovation of 12,000 sqft office space on floors 8-10. New HVAC, electrical, and buildout for tech company.",
    valuation: 2800000,
    applicant_raw: "Nexus Development LLC",
    contractor_raw: "Turner Construction Co",
    owner_raw: "Michigan Ave Properties Inc",
    expected_score_min: 70,
    expected_decision: "shortlisted",
  },
  {
    city: "chicago",
    source_permit_id: "CHI-2024-002",
    filed_date: "2024-01-20",
    issued_date: null,
    address_raw: "456 W Randolph St Chicago IL 60606",
    address_norm: "456 w randolph st chicago il 60606",
    work_type: "mixed_use",
    description_raw: "New construction 24-story mixed use tower: 180 residential units above 8,000 sqft retail. Full MEP.",
    valuation: 42000000,
    applicant_raw: "Randolph Group Partners",
    contractor_raw: "Skanska USA Building",
    owner_raw: "Randolph Group Partners",
    expected_score_min: 80,
    expected_decision: "shortlisted",
  },
  {
    city: "chicago",
    source_permit_id: "CHI-2024-003",
    filed_date: "2024-02-01",
    issued_date: "2024-02-28",
    address_raw: "789 S Wabash Ave Chicago IL 60605",
    address_norm: "789 s wabash ave chicago il 60605",
    work_type: "residential",
    description_raw: "Single family home addition - rear deck and kitchen remodel",
    valuation: 45000,
    applicant_raw: "John Smith",
    contractor_raw: "ABC Remodeling",
    owner_raw: "John Smith",
    expected_score_min: 0,
    expected_decision: "rejected",
  },
  {
    city: "chicago",
    source_permit_id: "CHI-2024-004",
    filed_date: "2024-02-10",
    issued_date: null,
    address_raw: "1234 W Fulton Market Chicago IL 60607",
    address_norm: "1234 w fulton market chicago il 60607",
    work_type: "industrial",
    description_raw: "Conversion of warehouse to food production facility. New equipment installation, cold storage, loading docks.",
    valuation: 5200000,
    applicant_raw: "Midwest Foods Processing Corp",
    contractor_raw: "Power Construction",
    owner_raw: "Fulton Market Holdings LLC",
    expected_score_min: 70,
    expected_decision: "shortlisted",
  },
  {
    city: "chicago",
    source_permit_id: "CHI-2024-005",
    filed_date: "2024-03-01",
    issued_date: "2024-03-15",
    address_raw: "200 E Randolph St Chicago IL 60601",
    address_norm: "200 e randolph st chicago il 60601",
    work_type: "office",
    description_raw: "Full floor buildout 28,000 sqft for financial services firm. New conference rooms, trading floor.",
    valuation: 6100000,
    applicant_raw: "LaSalle Capital Group",
    contractor_raw: "Leopardo Companies",
    owner_raw: "Aon Center LLC",
    expected_score_min: 75,
    expected_decision: "shortlisted",
  },

  // ---- Seattle ----
  {
    city: "seattle",
    source_permit_id: "SEA-2024-001",
    filed_date: "2024-01-10",
    issued_date: "2024-02-05",
    address_raw: "1000 2nd Ave Seattle WA 98104",
    address_norm: "1000 2nd ave seattle wa 98104",
    work_type: "commercial",
    description_raw: "TI for 15,000 sqft tech office. Open floor plan, new MEP, seismic retrofit of existing structure.",
    valuation: 3400000,
    applicant_raw: "Pacific Tech Realty",
    contractor_raw: "Sellen Construction",
    owner_raw: "Second Ave Holdings LLC",
    expected_score_min: 70,
    expected_decision: "shortlisted",
  },
  {
    city: "seattle",
    source_permit_id: "SEA-2024-002",
    filed_date: "2024-01-25",
    issued_date: null,
    address_raw: "401 Terry Ave N Seattle WA 98109",
    address_norm: "401 terry ave n seattle wa 98109",
    work_type: "medical",
    description_raw: "New 45,000 sqft medical office building. Surgical suites, imaging center, outpatient clinic.",
    valuation: 18500000,
    applicant_raw: "Northwest Health Properties",
    contractor_raw: "Skanska Healthcare",
    owner_raw: "Northwest Health Properties",
    expected_score_min: 80,
    expected_decision: "shortlisted",
  },
  {
    city: "seattle",
    source_permit_id: "SEA-2024-003",
    filed_date: "2024-02-15",
    issued_date: "2024-03-01",
    address_raw: "500 Mercer St Seattle WA 98109",
    address_norm: "500 mercer st seattle wa 98109",
    work_type: "fence",
    description_raw: "Replace fence around commercial property",
    valuation: 8000,
    applicant_raw: "Mercer Properties",
    contractor_raw: "Seattle Fencing Co",
    owner_raw: "Mercer Properties",
    expected_score_min: 0,
    expected_decision: "rejected",
  },
  {
    city: "seattle",
    source_permit_id: "SEA-2024-004",
    filed_date: "2024-02-20",
    issued_date: null,
    address_raw: "2201 Westlake Ave N Seattle WA 98109",
    address_norm: "2201 westlake ave n seattle wa 98109",
    work_type: "hotel",
    description_raw: "New 12-story hotel tower. 220 rooms, restaurant, conference center. $85M development.",
    valuation: 85000000,
    applicant_raw: "Westlake Hotel Investors LLC",
    contractor_raw: "Hoffman Construction",
    owner_raw: "Westlake Hotel Investors LLC",
    expected_score_min: 85,
    expected_decision: "shortlisted",
  },
  {
    city: "seattle",
    source_permit_id: "SEA-2024-005",
    filed_date: "2024-03-05",
    issued_date: null,
    address_raw: "801 2nd Ave Seattle WA 98104",
    address_norm: "801 2nd ave seattle wa 98104",
    work_type: "retail",
    description_raw: "Ground floor retail buildout 4,500 sqft. National grocery chain anchor tenant.",
    valuation: 890000,
    applicant_raw: "Urban Retail Partners",
    contractor_raw: "Pacific Rim Construction",
    owner_raw: "Seattle Urban Core LLC",
    expected_score_min: 60,
    expected_decision: "shortlisted",
  },

  // ---- Denver ----
  {
    city: "denver",
    source_permit_id: "DEN-2024-001",
    filed_date: "2024-01-08",
    issued_date: "2024-02-12",
    address_raw: "1700 Lincoln St Denver CO 80203",
    address_norm: "1700 lincoln st denver co 80203",
    work_type: "office",
    description_raw: "22,000 sqft creative office TI. Open plan, collaborative spaces, rooftop access improvements.",
    valuation: 4100000,
    applicant_raw: "Mountain West Development",
    contractor_raw: "Hensel Phelps",
    owner_raw: "Lincoln Street LLC",
    expected_score_min: 70,
    expected_decision: "shortlisted",
  },
  {
    city: "denver",
    source_permit_id: "DEN-2024-002",
    filed_date: "2024-01-18",
    issued_date: null,
    address_raw: "4800 E Evans Ave Denver CO 80222",
    address_norm: "4800 e evans ave denver co 80222",
    work_type: "warehouse",
    description_raw: "New 120,000 sqft distribution warehouse. 40' clear height, 40 dock doors, 3 drive-in doors.",
    valuation: 22000000,
    applicant_raw: "Rocky Mountain Logistics",
    contractor_raw: "GE Johnson Construction",
    owner_raw: "Evans Industrial Holdings",
    expected_score_min: 80,
    expected_decision: "shortlisted",
  },
  {
    city: "denver",
    source_permit_id: "DEN-2024-003",
    filed_date: "2024-02-05",
    issued_date: "2024-02-20",
    address_raw: "",
    address_norm: "",
    work_type: "commercial",
    description_raw: "Interior work",
    valuation: 600000,
    applicant_raw: "Anon LLC",
    contractor_raw: "",
    owner_raw: "",
    expected_score_min: 0,
    expected_decision: "rejected", // no address
  },
  {
    city: "denver",
    source_permit_id: "DEN-2024-004",
    filed_date: "2024-02-12",
    issued_date: null,
    address_raw: "1400 Wynkoop St Denver CO 80202",
    address_norm: "1400 wynkoop st denver co 80202",
    work_type: "multifamily",
    description_raw: "New 180-unit apartment tower, 12 stories, ground floor retail. Located in LoDo district.",
    valuation: 38000000,
    applicant_raw: "LoDo Residential Partners",
    contractor_raw: "Mortenson Construction",
    owner_raw: "Wynkoop Development LLC",
    expected_score_min: 75,
    expected_decision: "shortlisted",
  },
  {
    city: "denver",
    source_permit_id: "DEN-2024-005",
    filed_date: "2024-03-01",
    issued_date: "2024-03-10",
    address_raw: "999 18th St Denver CO 80202",
    address_norm: "999 18th st denver co 80202",
    work_type: "institutional",
    description_raw: "University campus building expansion - 35,000 sqft STEM research facility.",
    valuation: 28000000,
    applicant_raw: "Colorado University Foundation",
    contractor_raw: "Mortenson Construction",
    owner_raw: "Regents of the University of Colorado",
    expected_score_min: 75,
    expected_decision: "shortlisted",
  },

  // ---- Cincinnati ----
  {
    city: "cincinnati",
    source_permit_id: "CIN-2024-001",
    filed_date: "2024-01-12",
    issued_date: "2024-02-01",
    address_raw: "580 Building 301 E 4th St Cincinnati OH 45202",
    address_norm: "301 e 4th st cincinnati oh 45202",
    work_type: "commercial",
    description_raw: "Historic renovation of 8-story office building in CBD. Full gut rehab, 60,000 sqft.",
    valuation: 14000000,
    applicant_raw: "Cincinnati Heritage LLC",
    contractor_raw: "Turner Construction",
    owner_raw: "Fourth Street Properties",
    expected_score_min: 75,
    expected_decision: "shortlisted",
  },
  {
    city: "cincinnati",
    source_permit_id: "CIN-2024-002",
    filed_date: "2024-01-22",
    issued_date: null,
    address_raw: "2700 Madison Rd Cincinnati OH 45208",
    address_norm: "2700 madison rd cincinnati oh 45208",
    work_type: "retail",
    description_raw: "Neighborhood shopping center renovation. 28,000 sqft. Anchor tenant: grocery store.",
    valuation: 3800000,
    applicant_raw: "Madison Road Properties",
    contractor_raw: "Phillips Edison",
    owner_raw: "Madison Road Properties",
    expected_score_min: 65,
    expected_decision: "shortlisted",
  },
  {
    city: "cincinnati",
    source_permit_id: "CIN-2024-003",
    filed_date: "2024-02-08",
    issued_date: "2024-03-01",
    address_raw: "100 E Central Pkwy Cincinnati OH 45202",
    address_norm: "100 e central pkwy cincinnati oh 45202",
    work_type: "sign",
    description_raw: "New business signage installation",
    valuation: 5000,
    applicant_raw: "Downtown Signs LLC",
    contractor_raw: "Cincinnati Sign Co",
    owner_raw: "Downtown Retail LLC",
    expected_score_min: 0,
    expected_decision: "rejected",
  },
  {
    city: "cincinnati",
    source_permit_id: "CIN-2024-004",
    filed_date: "2024-02-14",
    issued_date: null,
    address_raw: "3800 Red Bank Rd Cincinnati OH 45227",
    address_norm: "3800 red bank rd cincinnati oh 45227",
    work_type: "manufacturing",
    description_raw: "New 200,000 sqft manufacturing facility - automotive components. Rail access.",
    valuation: 45000000,
    applicant_raw: "Midwest Auto Parts LLC",
    contractor_raw: "Messer Construction",
    owner_raw: "Red Bank Industrial Park LLC",
    expected_score_min: 85,
    expected_decision: "shortlisted",
  },
  {
    city: "cincinnati",
    source_permit_id: "CIN-2024-005",
    filed_date: "2024-02-28",
    issued_date: null,
    address_raw: "201 E 5th St Cincinnati OH 45202",
    address_norm: "201 e 5th st cincinnati oh 45202",
    work_type: "mixed_use",
    description_raw: "Adaptive reuse of former department store to hotel + office + retail. 12 floors, 220,000 sqft.",
    valuation: 62000000,
    applicant_raw: "Fifth Street Redevelopment LLC",
    contractor_raw: "Messer Construction",
    owner_raw: "Fifth Street Redevelopment LLC",
    expected_score_min: 85,
    expected_decision: "shortlisted",
  },

  // ---- Austin ----
  {
    city: "austin",
    source_permit_id: "AUS-2024-001",
    filed_date: "2024-01-05",
    issued_date: "2024-02-15",
    address_raw: "600 Congress Ave Austin TX 78701",
    address_norm: "600 congress ave austin tx 78701",
    work_type: "office",
    description_raw: "Full floor TI for tech company - 18,000 sqft. Custom buildout including lab space.",
    valuation: 5400000,
    applicant_raw: "Austin Tech Properties",
    contractor_raw: "Balfour Beatty Construction",
    owner_raw: "Congress Ave Towers LLC",
    expected_score_min: 75,
    expected_decision: "shortlisted",
  },
  {
    city: "austin",
    source_permit_id: "AUS-2024-002",
    filed_date: "2024-01-19",
    issued_date: null,
    address_raw: "3900 N Interstate 35 Austin TX 78722",
    address_norm: "3900 n interstate 35 austin tx 78722",
    work_type: "data_center",
    description_raw: "New 80,000 sqft hyperscale data center. 30 MW capacity. Mission critical construction.",
    valuation: 125000000,
    applicant_raw: "Texas Data Infrastructure LLC",
    contractor_raw: "Turner Construction",
    owner_raw: "Texas Data Infrastructure LLC",
    expected_score_min: 90,
    expected_decision: "shortlisted",
  },
  {
    city: "austin",
    source_permit_id: "AUS-2024-003",
    filed_date: "2024-01-29",
    issued_date: "2024-02-25",
    address_raw: "1515 S Capital of Texas Hwy Austin TX 78746",
    address_norm: "1515 s capital of texas hwy austin tx 78746",
    work_type: "plumbing_only",
    description_raw: "Plumbing replacement for commercial building",
    valuation: 55000,
    applicant_raw: "Austin Plumbing Co",
    contractor_raw: "Austin Plumbing Co",
    owner_raw: "Texas Capital Properties",
    expected_score_min: 0,
    expected_decision: "rejected",
  },
  {
    city: "austin",
    source_permit_id: "AUS-2024-004",
    filed_date: "2024-02-18",
    issued_date: null,
    address_raw: "500 W 5th St Austin TX 78701",
    address_norm: "500 w 5th st austin tx 78701",
    work_type: "hotel",
    description_raw: "Boutique hotel conversion of historic office building. 140 rooms, rooftop bar, spa.",
    valuation: 28000000,
    applicant_raw: "Fifth Street Hospitality",
    contractor_raw: "Hensel Phelps",
    owner_raw: "Fifth Street Hospitality",
    expected_score_min: 80,
    expected_decision: "shortlisted",
  },
  {
    city: "austin",
    source_permit_id: "AUS-2024-005",
    filed_date: "2024-03-02",
    issued_date: null,
    address_raw: "2525 W Anderson Ln Austin TX 78757",
    address_norm: "2525 w anderson ln austin tx 78757",
    work_type: "new_construction",
    description_raw: "New construction community college campus building - 45,000 sqft. Classrooms, labs, student services.",
    valuation: 31000000,
    applicant_raw: "Austin Community College District",
    contractor_raw: "DPR Construction",
    owner_raw: "Austin Community College District",
    expected_score_min: 75,
    expected_decision: "shortlisted",
  },
];

// Duplicate entity test pair (same contractor, different names)
const DUPLICATE_ENTITY_PAIR = {
  entity1_name: "Turner Construction Co",
  entity1_norm: "turner construction co",
  entity2_name: "Turner Construction Company",
  entity2_norm: "turner construction company",
  expected_match_tier: "probable",
};

module.exports = { fixtures, DUPLICATE_ENTITY_PAIR };
